version: '3.5'

networks:
  ideafast-etl:
    external: true
  web:
    external: true

services:
  api:
    image: ideafast/wp3api:latest
    restart: always
    ports:
      - "80:80"
    environment:
      APP_MODULE: api.main:api
    env_file:
      - .env
    networks:
      - ideafast-etl
      - web
