version: '3.5'

services:
  api:
    image: ideafast/wp3api:latest
    restart: 'no'
    ports:
      - "80:80"
    environment:
      APP_MODULE: api.main:api
    env_file:
      - .env
    volumes:
      - ./ssh:/root/.ssh
