version: '3.5'

services:
  api:
    image: ideafast/wp3api:latest
    restart: 'no'
    ports:
      - "80:80"
    environment:
      APP_MODULE: api.main:api
    env_file:
      - .env
    volumes:
      - ./ssh:/root/.ssh
      - ./insert_credentials:/app/insert_credentials

  mongo:
    container_name: mongo_credentials
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${_MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${_MONGO_INITDB_DATABASE}
      MONGO_INITDB_HOST: ${_MONGO_INITDB_HOST}
      MONGO_INITDB_COLLECTION: ${_MONGO_INITDB_COLLECTION}
    ports:
      - '27017:27017'
    volumes:
      - mongo-db-volume:/data/db
      - ./init/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

volumes:
  mongo-db-volume: null
